spring:
  application:
    name: demo-annotation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_demo?&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      minimum-idle: 10
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 600000
      pool-name: AnnotationDateSourceHikariCP
      max-lifetime: 1800000


# mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: DEBUG
