server:
  port: 18888
  shutdown: graceful

spring:
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: mybatis
    password: 3jq^edM#nW5J
    # 各个参数的含义
    # useUnicode：使用Unicode字符集进行通信
    # characterEncoding：字符串数据以UTF-8编码进行传
    # serverTimezone：服务器的时区设定为亚洲上海时区，以匹配应用程序的预期时区设置。
    url: jdbc:p6spy:mysql://106.15.104.240:3306/mybatis?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    # 配置连接池，MySQL数据库默认支持2000个数据连接
    hikari:
      # 测试连接是否可用
      connection-test-query: select 1
      # 连接超时时间，单位是毫秒
      connection-timeout: 30000
      # 空闲连接超时时间，单位是毫秒
      idle-timeout: 600000
      # 保持连接最长时间，单位是毫秒
      max-lifetime: 1800000
      # 最大连接数
      maximum-pool-size: 10
      # 最小空闲连接数
      minimum-idle: 10

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true
  global-config:
    banner: true
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto

#p6spy:
#  config:
#    logMessageFormat: com.baomidou.mybatisplus.extension.p6spy.P6SpyLogger
#    moduleList: com.baomidou.mybatisplus.extension.p6spy.MybatisPlusLogFactory,com.p6spy.engine.outage.P6OutageFactory
#    appender: com.p6spy.engine.spy.appender.Slf4JLogger
#    deregisterDrivers: true
#    usePrefix: true
#    excludeCategories: info,debug,result,commit,resultset



#decorator:
#  datasource:
#    datasource-proxy:
#      query:
#        log-level: debug
#        enable-logging: true
#      logging: slf4j
#    p6spy:
#      enable-logging: true
#      logging: slf4j

jackson:
  module: