server:
  port: 18888
  shutdown: graceful

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mybatis
    password: 3jq^edM#nW5J
    # 各个参数的含义
    # useUnicode：使用Unicode字符集进行通信
    # characterEncoding：字符串数据以UTF-8编码进行传
    # serverTimezone：服务器的时区设定为亚洲上海时区，以匹配应用程序的预期时区设置。
    url: jdbc:mysql://106.15.104.240:3306/mybatis?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    # 配置连接池，MySQL数据库默认支持2000个数据连接
    hikari:
      # 测试连接是否可用
      connection-test-query: select 1
      # 连接超时时间，单位是毫秒
      connection-timeout: 30000
      # 空闲连接超时时间，单位是毫秒
      idle-timeout: 600000
      # 保持连接最长时间，单位是毫秒
      max-lifetime: 1800000
      # 最大连接数
      maximum-pool-size: 10
      # 最小空闲连接数
      minimum-idle: 10

mybatis:
  # 配置XML文件的位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
    cache-enabled: true
    use-generated-keys: true
    default-fetch-size: 1000
    default-statement-timeout: 1000
    cache-miss-null-object: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    use-actual-column-names: true
    use-column-label: true

#logging:
#  level:
#    org.apache.ibatis: debug
