spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.116.58.10:3306/pyspider_sit_resultdb?charset=utf8mb4&useSSL=false
    password: ND0328qSywfre
    username: pyspider_user
    hikari:
      connection-timeout: 30000
      minimum-idle: 10
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 600000
      pool-name: AuditDateSourceHikariCP
      max-lifetime: 1800000
