server:
  port: 18888
  shutdown: graceful

spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: mybatis
          password: 3jq^edM#nW5J
          url: jdbc:mysql://106.15.104.240:3306/mybatis?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
          # 配置连接池，MySQL数据库默认支持2000个数据连接
          hikari:
            # 测试连接是否可用
            connection-test-query: select 1
            # 连接超时时间，单位是毫秒
            connection-timeout: 30000
            # 空闲连接超时时间，单位是毫秒
            idle-timeout: 600000
            # 保持连接最长时间，单位是毫秒
            max-lifetime: 1800000
            # 最大连接数
            maximum-pool-size: 10
            # 最小空闲连接数
            minimum-idle: 10
        # 这个命名不一定代表是主从库的关系，可以改为具体的业务名称
        # slave1:
        #   driver-class-name: com.mysql.cj.jdbc.Driver
        #   username: mybatis
        #   password: 3jq^edM#nW5J
        #   url: jdbc:mysql://106.15.104.240:3306/mybatis?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        #   # 配置连接池，MySQL数据库默认支持2000个数据连接
        #   hikari:
        #     # 测试连接是否可用
        #     connection-test-query: select 1
        #     # 连接超时时间，单位是毫秒
        #     connection-timeout: 30000
        #     # 空闲连接超时时间，单位是毫秒
        #     idle-timeout: 600000
        #     # 保持连接最长时间，单位是毫秒
        #     max-lifetime: 1800000
        #     # 最大连接数
        #     maximum-pool-size: 10
        #     # 最小空闲连接数
        #     minimum-idle: 10
        doc:
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: doc
          password: UsK#28%*quE4uv
          url: jdbc:mysql://106.15.104.240:3306/doc?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
          # 配置连接池，MySQL数据库默认支持2000个数据连接
          hikari:
            # 测试连接是否可用
            connection-test-query: select 1
            # 连接超时时间，单位是毫秒
            connection-timeout: 30000
            # 空闲连接超时时间，单位是毫秒
            idle-timeout: 600000
            # 保持连接最长时间，单位是毫秒
            max-lifetime: 1800000
            # 最大连接数
            maximum-pool-size: 10
            # 最小空闲连接数
            minimum-idle: 10
